[default]
duration = "30m"
mode = "center"

[DP-1]
path = "/home/matan/.config/wallpapers/1st_monitor.png"

[DP-3]
path = "/home/matan/.config/wallpapers/2nd_monitor.png"

[HDMI-A-3]
path = "/home/matan/.config/wallpapers/2nd_monitor.png"
