[default]
duration = "30m"
mode = "center"

[DP-1]
path = "/home/matan/.config/wallpapers/2k/"

[DP-3]
path = "/home/matan/.config/wallpapers/1080/"

[HDMI-A-3]
path = "/home/matan/.config/wallpapers/2k/"
